# Minimal LiteLLM proxy config
general_settings:
  master_key: ${LITELLM_API_KEY:-sk-demo-virtual-key}

proxy_server:
  host: 0.0.0.0
  port: 4000

model_list:
  # OpenRouter (default)
  - model_name: openrouter/auto
    litellm_params:
      model: openrouter/auto
      api_base: https://openrouter.ai/api/v1
      api_key: ${OPENROUTER_API_KEY}

  # OpenAI example
  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: gpt-4o-mini
      api_key: ${OPENAI_API_KEY}

  # Anthropic example
  - model_name: anthropic/claude-3-5-sonnet
    litellm_params:
      model: claude-3-5-sonnet-20241022
      api_key: ${ANTHROPIC_API_KEY}
